title: "TF 5 - TPs"
theme: minima

markdown: kramdown
layouts_dir: layout

kramdown:
  parse_block_html: true

collections:
  tp:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "tp"
    values:
      layout: "tp"